[package]
name = "pymut"
version = "0.1.0"
authors = ["Chuck Rai <cprai@sfu.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustpython-parser = "0.1.1"